[general]
#General Configurable Attributes for the Task Navigator Application
vault=/home/brian/Documents/src/python/Task Navigator v2/taskNavigator/vault
top_level_filename=Top Level Process
installation_path=/home/brian/Documents/src/python/Task Navigator v2/taskNavigator
window_width = 720
window_height = 1500
debug=True