[app]
background_color=darkest grayish blue

[action_widget]
background_color=darkest gray
font_color=white

[entry_widget]
background_color=black
highlight_color=darkest cyan
font_color=white

[font]
typeface=bitstream charter
size=28

#fangsong ti
#fixed
#clearlyu alternate glyphs
#courier 10 pitch
#open look glyph
#bitstream charter
#song ti
#open look cursor
#newspaper
#clearlyu ligature
#mincho
#clearlyu devangari extra
#clearlyu pua
#clearlyu
#clean
#nil
#clearlyu arabic
#clearlyu devanagari
#gothic
#clearlyu arabic extra